name: Build and Publish Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: Ian_Dunn_Resume.tex
        args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode

    - name: Create or Update Latest Release
      uses: ncipollo/release-action@v1
      with:
        tag: latest
        name: Latest Resume
        files: Ian_Dunn_Resume.pdf
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        keep_files: true
