name: Build and Publish Resume

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: Ian_Dunn_Resume.tex

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pdf-${{ github.run_number }}
          name: "PDF Resume ${{ github.run_number }}"
          body: ${{ github.event.head_commit.message }}
          files: Ian_Dunn_Resume.pdf
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Site Directory
        run: |
          mkdir site
          rsync -av --exclude '.git' --exclude '.github' ./ site/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

